name: Build Private Image

on: [push]

jobs:
  build-step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: docker build & push
        env:
          DockerPassword: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          docker build -f Dockerfile.private --no-cache --build-arg GATEWAY=pay.tf/pay/proc/new -t docker.pkg.github.com/naiba/qiongbi/web .
          docker login -u naiba -p $DockerPassword docker.pkg.github.com
          docker push docker.pkg.github.com/naiba/qiongbi/web